argocdNamespace: argocd
destinationNamespace: default
spec:
  destination:
    name: "target-cluster"
  source:
    repoURL: "https://github.com/indranil-avyka/argocd-example-apps.git"
    targetRevision: HEAD

applications:
  - name: app1
    path: charts/app1
    helm: true       
  - name: app2
    path: charts/app2
    helm: true       
  - name: helm-guestbook
    path: helm-guestbook
    helm: true        
